components/Layout.js, package-lock.json, package.json, routes/apiRoutes.js, server.js
When you register as a new user, bcrypt now encrypts the user's password
=> user password is now encrypted

pages/Projects.js, routes/apiRoutes.js
Whenever a user logs in, the project dashboard will now get all the user's projects and display them
=> project-dashboard now shows all the user's projects

components/FormIndividualTasks.js, components/FormIndividualTeam.js, components/FormNewProject.js, components/FormTeam.js, pages/NewProject.js
Altered forms so that email is a property of the Collaborator object.
=> altered forms

components/FormNewProject.js, components/NavDropdown.js, components/NewTeam.js, pages/NewProject.js, server.js
You can now dynamically create a new team field, and submit all the project info successfully into the DB
=> dynamically create new teams and add to DB

components/DashboardTasks.js, components/NPCard.js, components/PCard.js, pages/DashboardTest.js, pages/Projects.js
I made some minor changes to the styles of the project cards. It isn't much. I made it so the cards all have a standard height and that there is a headline for the section. Initially I was working on tasks but I ended up reprioritizing.
=> minor changes to project pages cards

components/NewCollaborator.js, pages/NewProject.js, routes/apiRoutes.js
You can search and add for collaborators who are registered with the app.
Whenever you create the project with collaborators, the project will show up on the collaborators project dashboard.
=> you can now add collaborators to the project

components/DashboardTasks/index.js
=> new task form with new file structure

components/DashboardTasks/index.js, models/tasks.js, pages/project/[id].js, routes/apiRoutes.js
1) Translated DashboardTask from hooks to stateful
2) You can create a new task from the task portion of the project page
=> you can now create a task and insert it into the db

components/DashboardTasks/index.js
Returns to tasks after submission
=> added function to take users back to all tasks

components/DashboardLayout/_style.scss, components/DashboardLayout/index.js, components/DashboardWindow/index.js, components/Layout/index.js, components/NPCard/_style.scss, components/NPLayout/styles.css, components/NPLayout/styles.css.map, pages/Dashboard.js, pages/DashboardTest.js, pages/NewProject.js, pages/login.js, pages/register.js, pages/teamPage.js, pages/tickTest.js, styles.scss
small changes to style - nothing set in stone or complete
=> working with monica deciding styles

components/NPForm/index.js, pages/NewProject.js
Splits portions of the new project page in the multiple "slides" with next and last buttons to move
=> Seperating new projectpage

pages/project/[id].js, pages/teamPage.js
This should hopefully fix all the heroku errors
=> fixing heroku errs

components/DashboardTasks/index.js, pages/login.js, pages/register.js
Updated New Task Error Message
=> added error message to Login & New Task

components/DashboardTasks/index.js, routes/apiRoutes.js
You can now click 'claim task' and it will insert the user.id into the DB and update the task status. Right now, the page will only render tasks that are in the 'unassigned' status, so after you claim a task, it does not render on the page.
=> you can now claim tasks

components/DashboardTasks/index.js
1) Task creation no longer goes to the form, but rather creates a new card for you to edit
-I think this new method is a lot more informative to the user. Give them direct feedback on the 
screen of what their new task will look like
=> adding-new-task

components/DashboardTasks/_style.scss, components/DashboardTasks/index.js, pages/project/[id].js, styles.scss
Style changes made to tasks page. In first iteration of changes - I haven't gotten the priority levels colors to swap yet but I think I'm close.
=> Task project style

components/DashboardTasks/index.js, routes/apiRoutes.js
you can now select the status of your tasks which updated the DB with the correct info
=> you can now set status of your tasks

components/CreatedProject/index.js, components/DashboardTasks/index.js, components/NPLayout/index.js, components/NPLayout/style.scss, components/RLLayout/index.js, pages/login.js, pages/register.js, styles.scss
Created delete buttons for the tasks.
A confirmation modal is triggered by the x, and pressing delete triggers handleDeleteTask which is currently just a console.log
=> created delete buttons on tasks

components/DashboardTeams/index.js, models/collaborator.js, pages/project/[id].js, routes/apiRoutes.js
1) teams tab now lists all the teams
2) click on the team, and it will select all the users
3) click on the user and you can view all their tasks and assign them to a new team
=> you can now see all teams and update

components/NPCard/index.js, pages/login.js, pages/register.js
1) 'New Project' btn now redirects to 'newProject' rather than 'NewProject'
2) After registering, it takes you to login and shows a new message
=> fixing new project route and register-login

components/DashboardTasks/_style.scss, components/DashboardTasks/index.js, pages/project/[id].js, styles.scss
Edits to: 
Nav Bar on tasks page
Buttons (no more shaky thing)
Hover on Links
Full page projects
=> Styles danielle update

components/DashboardTasks/index.js, components/DashboardTeams/index.js, components/NewCollaborator/index.js
Created a form for adding new collaborators to the project and assigning them to a team.
=> created form for new collaborators on teams section

components/DashboardTasks/index.js
Error message appears if the user does not enter task name and description
=> added back validation

components/DashboardTeams/index.js, routes/apiRoutes.js
1) Allows the user to add collaborators to the project
=> you can now add collabs to the project

components/DashboardTasks/_style.scss, components/DashboardTasks/index.js
Added buttons for showing complete/ in progress tasks
=> added complete/in progress buttons

components/DashboardTeams/index.js, models/notifications.js, pages/newProject.js, pages/projects.js, routes/apiRoutes.js
1) when adding collaborators to the project, it no longer automatically adds you to the project, but it will invite you instead
=> Notification system

components/DashboardTasks/index.js
*What this does**
1) adding the ability to delete tasks again
=> re-adding deleting tasks

components/Nav/index.js
This is the 'welcome' message when you are logged in.
=> used hooks to get dynamically displayed name

components/NPForm/index.js, pages/newProject.js
=> showing user feedback when adding collabs

components/DashboardTasks/_style.scss, components/DashboardTasks/index.js, styles.scss
Adds borders to tasks based on the priority level and status of the task. As of now, the information is still written out on the card.
=> Task borders

pages/newProject.js, pages/notifications.js, pages/project/[id].js, pages/projects.js
Changes notifications to a page, links from nav dropdown menu
=> Notifications

components/DashboardTasks/_style.scss, components/DashboardTasks/index.js
=> Task buttons

components/DashboardTeams/_style.scss, components/DashboardTeams/index.js, styles.scss
=> Teams rework

components/DashboardTasks/index.js
=> adding some small changes

components/DashboardTasks/index.js
1) You can only create one task
2) New task textboxes get reset
=> fixing some small bugs for new task
